---
# Environment variables prefix: NT (prefix + "_" + the key name)
development: true
host: localhost
port: 8080

static_paths:
  [
    ["/docs/*", "../../nervatura-docs/docs"],
    ["/report/*", "../../nervatura-demo/docs"],
    ["/client/*", "../../nervatura-client/build"]
  ]

# Server CORS settings
cors:
  # Defines a list of origins that may access the resource.
  allow_origins: ["*"]
  # Defines a list methods allowed when accessing the resource.
  allow_methods: ["GET","HEAD","PUT","PATCH","POST","DELETE"]
  # Defines a list of request headers that can be used when making the actual request.
  allow_headers: []
  # Indicates whether or not the response to the request can be exposed when the credentials flag is true.
  allow_credentials: false
  # ExposeHeaders defines a whitelist headers that clients are allowed to access.
  expose_headers: []
  # Indicates how long (in seconds) the results of a preflight request can be cached
  max_age: 0

# Server security settings
# See more: github.com/unrolled/secure (default options)
security:
  allowed_hosts: []
  allowed_hosts_are_regex: false
  hosts_proxy_headers: []
  ssl_redirect: false
  ssl_temporary_redirect: false
  ssl_host:
  ssl_proxy_headers:
  sts_seconds: 0
  sts_include_subdomains: false
  sts_preload: false
  force_sts_header: false
  frame_deny: false
  custom_frame_options_value:
  content_type_nosniff: false
  browser_xss_filter: false
  content_security_policy:
  public_key:
  referrer_policy:
  feature_policy:
  expect_ct_header:
...