# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: nervatura
release:
  disable: true
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: all
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    binary: nervatura
    tags:
      - all
    hooks:
      post:
       - upx --best --lzma "{{ .Path }}"
archives:
  - builds:
      - all
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapcrafts:
  -
    id: nervatura
    publish: false
    builds:
      - all
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    summary: Open Source Business Management Framework
    description: |
      Nervatura is a business management framework. It can handle any type of business related information, starting from customer details, up to shipping, stock or payment information.
    grade: stable
    confinement: strict
    license: LGPL-3.0-or-later
    apps:
      nervatura:
        plugs: ["network","network-bind","home"]
        daemon: simple
        restart_condition: always
